//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_TestApp.msgServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WireMessage", Namespace="http://schemas.datacontract.org/2004/07/TC_WS")]
    [System.SerializableAttribute()]
    public partial class WireMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recipientUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderUserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msgText {
            get {
                return this.msgTextField;
            }
            set {
                if ((object.ReferenceEquals(this.msgTextField, value) != true)) {
                    this.msgTextField = value;
                    this.RaisePropertyChanged("msgText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recipientUserId {
            get {
                return this.recipientUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.recipientUserIdField, value) != true)) {
                    this.recipientUserIdField = value;
                    this.RaisePropertyChanged("recipientUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string senderUserId {
            get {
                return this.senderUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.senderUserIdField, value) != true)) {
                    this.senderUserIdField = value;
                    this.RaisePropertyChanged("senderUserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="msgServiceReference.IMsgService")]
    public interface IMsgService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMsgService/postMessage", ReplyAction="http://tempuri.org/IMsgService/postMessageResponse")]
        bool postMessage(string receiverId, string senderId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMsgService/getMyMessages", ReplyAction="http://tempuri.org/IMsgService/getMyMessagesResponse")]
        WS_TestApp.msgServiceReference.WireMessage[] getMyMessages(string receiverId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMsgServiceChannel : WS_TestApp.msgServiceReference.IMsgService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsgServiceClient : System.ServiceModel.ClientBase<WS_TestApp.msgServiceReference.IMsgService>, WS_TestApp.msgServiceReference.IMsgService {
        
        public MsgServiceClient() {
        }
        
        public MsgServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MsgServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool postMessage(string receiverId, string senderId, string message) {
            return base.Channel.postMessage(receiverId, senderId, message);
        }
        
        public WS_TestApp.msgServiceReference.WireMessage[] getMyMessages(string receiverId) {
            return base.Channel.getMyMessages(receiverId);
        }
    }
}
