<?xml version="1.0" encoding="utf-8"?><Database Name="tinycircle" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=z082ai5xw0.database.windows.net;Initial Catalog=tinycircle;Persist Security Info=True;User ID=Mestari" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="tinycircleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="SenderID" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Payload" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>